language: cpp
os:
  - linux
  - osx
addons:
  apt:
    update: true
    sources:
    - sourceline: "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-9 main"
      key_url: "https://apt.llvm.org/llvm-snapshot.gpg.key"
    packages:
    - gcc
    - g++
    - cmake
    - libgmp-dev
    - libboost-dev
    - libboost-filesystem-dev
    - libboost-thread-dev
    - libboost-test-dev
    - python
    - python-pygments
    - libsqlite3-dev
    - libtbb-dev
    - libz-dev
    - libedit-dev
    - llvm-9
    - llvm-9-dev
    - llvm-9-tools
    - clang-9
  homebrew:
    update: true
    taps: nasa-sw-vnv/core
    packages:
    - cmake
    - gmp
    - boost
    - tbb
    - llvm
    - apron
script:
  - mkdir build
  - cd build
  - if [ $TRAVIS_OS_NAME == linux ]; then cmake -DCMAKE_BUILD_TYPE="Debug" -DLLVM_CONFIG_EXECUTABLE="/usr/lib/llvm-9/bin/llvm-config" ..; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then cmake -DCMAKE_BUILD_TYPE="Debug" -DLLVM_CONFIG_EXECUTABLE="/usr/local/opt/llvm/bin/llvm-config" ..; fi
  - make
  - make install
  - make check
env:
  global:
    - MAKEFLAGS="-j2"
